version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agsistemasveiculos
      MYSQL_USER: agsistemasveiculos
      MYSQL_PASSWORD: agsistemasveiculos
    ports:
      -  "3306:3306"
    volumes:
      - ./data/db:/var/lib/postgresql/data