# Generated by Django 5.0.4 on 2024-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_motorista', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo do motorista (o id ja é o suficiente)')),
                ('nome', models.CharField(db_index=True, max_length=128, verbose_name='Nome do motorista')),
                ('telefone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telefone do motorista (whatsapp)')),
                ('cnh', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='CNH do motorista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Mtorista',
                'verbose_name_plural': 'Mtoristas',
                'db_table': 'motoristas',
                'managed': True,
            },
        ),
    ]
