# Generated by Django 5.0.4 on 2024-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='km_troca_oleo',
            field=models.IntegerField(default=10000, verbose_name='Km Troca Oleo'),
        ),
    ]
