# Generated by Django 5.0.4 on 2024-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleregistro',
            name='km_pecorrido',
            field=models.IntegerField(default=0, verbose_name='Km Percorrido (campo sera calculado automaticamente apos salvar)'),
        ),
    ]
