# Generated by Django 5.0.4 on 2024-04-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_controleregistro_km_pecorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleregistro',
            name='retorno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora do Retorno'),
        ),
        migrations.AlterField(
            model_name='controleregistro',
            name='saida',
            field=models.DateTimeField(verbose_name='Data e hora da Saida'),
        ),
    ]
