# Generated by Django 5.0.4 on 2024-05-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_veiculo_veiculo'),
        ('controle', '0004_alter_controleregistro_motorista_and_more'),
        ('motorista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleregistro',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='motorista.motorista'),
        ),
        migrations.AlterField(
            model_name='controleregistro',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='carro.veiculo'),
        ),
    ]
